"""Acceptance tests AT-01 … AT-22 — the definition of done (SPEC §11).

Every test below is a stub. Its docstring carries the fixture, the expected
strategy and the pass criteria exactly as SPEC §11 states them; the body is the
work item.

**Skipping.** SPEC §11: "Integration/acceptance tests are skipped until the
`expected/` files exist." Expected results — row counts, aggregate-checksum
vectors, Delta version ledgers, per-engine schemas — are recorded once by
`fsi-fixtures snapshot-golden` from the live sandbox estate into
`tests/fixtures/expected/<fixture>.json` and committed in a reviewer-approved
PR. They are **never** generated by `table-mcp` code (root rule 5). Until such a
file is committed, this whole module skips.

The strategy and type oracles (`expected/strategy.yaml`, `expected/types.yaml`)
are human-authored and drive the *unit* tests, which need no live estate.
"""

from __future__ import annotations

from pathlib import Path

import pytest

EXPECTED_DIR = Path(__file__).resolve().parents[1] / "fixtures" / "expected"

_GOLDEN_FILES = sorted(EXPECTED_DIR.glob("*.json"))

pytestmark = [
    pytest.mark.acceptance,
    pytest.mark.skipif(
        not _GOLDEN_FILES,
        reason=(
            "no golden fixtures in tests/fixtures/expected/ — record them once with "
            "`fsi-fixtures snapshot-golden` (SPEC §11); never generate them from this code"
        ),
    ),
]

_TODO = "acceptance test not implemented yet — scaffold only"


def test_at_01_trades_plain_metadata_only() -> None:
    """AT-01 · `trades_plain` (200M rows, identity partition by `trade_date`, no
    features) · expected strategy **S1**.

    Pass criteria: zero data copy; row count and checksums match; Athena,
    Redshift and EMR agree; completes in under 5 minutes.
    """
    pytest.fail(_TODO)


def test_at_02_positions_history_replay() -> None:
    """AT-02 · `positions_history` (50 versions over 90 days) with
    `history_days=60` · expected strategy **S2**.

    Pass criteria: at least 40 Iceberg snapshots tagged with their Delta
    versions; time-travel to 3 sampled versions matches Delta `VERSION AS OF`.
    """
    pytest.fail(_TODO)


def test_at_03_customers_dv_deletion_vectors() -> None:
    """AT-03 · `customers_dv` (deletion vectors enabled, 5% soft-deleted) ·
    expected strategy **S3**.

    Pass criteria: row count equals the Delta logical count with deleted rows
    excluded; checksums match.
    """
    pytest.fail(_TODO)


def test_at_04_ref_columns_id_mapping() -> None:
    """AT-04 · `ref_columns_idmap` (column mapping `id` mode, renamed and dropped
    columns in history) · expected strategy **S3**.

    Pass criteria: final schema matches; renamed columns carry their current
    names; the conversion record lists the schema evolution.
    """
    pytest.fail(_TODO)


def test_at_05_orders_cdf_changelog() -> None:
    """AT-05 · `orders_cdf` (physical table `meridian_fin.gl.journal_cdf`, CDF
    enabled, consumer identified in lineage) · expected strategy **S4**.

    Pass criteria: `journal_cdf__changes` exists with `_change_type` populated
    for the window; the consumer is flagged in the conversion record.
    """
    pytest.fail(_TODO)


def test_at_06_dlt_gold_risk_pipeline_gate() -> None:
    """AT-06 · `dlt_gold_risk` (DLT-managed, pipeline active) · expected strategy
    **S5 with S1 underlying**.

    Pass criteria: `execute_conversion` refuses while the pipeline is active;
    succeeds once it is paused; the record flags the pipeline for `jobs-mcp`.
    """
    pytest.fail(_TODO)


def test_at_07_mkt_data_uniform_bridge() -> None:
    """AT-07 · `mkt_data_uniform` (UniForm enabled) · expected strategy **S6**.

    Pass criteria: the table is not converted; the Glue bridge table reads in
    Athena; the record marks the eventual strategy.
    """
    pytest.fail(_TODO)


def test_at_08_events_variant_manual() -> None:
    """AT-08 · `events_variant` (a column of type VARIANT) · expected rule **S7**.

    Pass criteria: decision is `MANUAL` with a precise reason; no side effects.
    """
    pytest.fail(_TODO)


def test_at_09_tiny_files_compaction() -> None:
    """AT-09 · `tiny_files` (40k files, median 1.5 MB) · expected strategy **S3**.

    Pass criteria: output file count below 400; checksums match.
    """
    pytest.fail(_TODO)


def test_at_10_gen_partition_transform() -> None:
    """AT-10 · `gen_partition` (partitioned by a generated `year(ts)` column) ·
    expected strategy **S3 with the `year(ts)` transform**.

    Pass criteria: the partition spec uses the Iceberg transform; no generated
    column appears in the output schema; `add_files` is never attempted.
    """
    pytest.fail(_TODO)


def test_at_11_idempotency_resume() -> None:
    """AT-11 · Idempotency — kill AT-01 at 50% and re-run.

    Pass criteria: the run converges; no duplicate files; a single Glue table.
    """
    pytest.fail(_TODO)


def test_at_12_concurrency_locked() -> None:
    """AT-12 · Concurrency — the same table from two runs.

    Pass criteria: the second run is refused with `LOCKED`.
    """
    pytest.fail(_TODO)


def test_at_13_promotion_without_approval_id() -> None:
    """AT-13 · Promotion without an approval id.

    Pass criteria: `promote_table` refuses with `APPROVAL_REQUIRED`.
    """
    pytest.fail(_TODO)


def test_at_14_write_grant_refuses_startup() -> None:
    """AT-14 · A write grant is present on the service principal.

    Pass criteria: the server refuses to start and the error names the grant.
    """
    pytest.fail(_TODO)


def test_at_15_missing_kms_key() -> None:
    """AT-15 · Missing KMS key.

    Pass criteria: `execute_conversion` refuses before any S3 write.
    """
    pytest.fail(_TODO)


def test_at_16_estate_run() -> None:
    """AT-16 · Estate test — all fixtures through `plan_conversion` and
    `execute_conversion` · expected strategies **mixed**.

    Pass criteria: the full internal dataset (at least 1 TB) is staged,
    validated and read-checked in one run; total duration and cost are recorded
    for the TCO model.
    """
    pytest.fail(_TODO)


def test_at_17_stale_running_recovery() -> None:
    """AT-17 · Stale `RUNNING` — kill the worker mid-conversion, wait past the
    lease TTL, re-run.

    Pass criteria: the table is treated as `FAILED`; staging is cleaned; the run
    converges; the lock is re-acquired.
    """
    pytest.fail(_TODO)


def test_at_18_redaction_of_library_exception() -> None:
    """AT-18 · Redaction — force a PySpark exception containing a literal value.

    Pass criteria: the logged `ErrorEnvelope` contains no quoted literals and no
    partition values.
    """
    pytest.fail(_TODO)


def test_at_19_orphaned_emr_job_recovery() -> None:
    """AT-19 · Orphaned EMR job — kill the orchestrator, leave the Spark job
    running, then recover.

    Pass criteria: recovery cancels the job run before any cleanup; no Glue
    table or metadata from the orphan survives.
    """
    pytest.fail(_TODO)


def test_at_20_history_not_preserved_warning() -> None:
    """AT-20 · `positions_history_dv` (a copy of `positions_history` with
    deletion vectors enabled) with `history_days=60` · expected strategy **S3**.

    Pass criteria: the warning `HISTORY_NOT_PRESERVED` is present in both the
    decision and the conversion record.
    """
    pytest.fail(_TODO)


def test_at_21_athena_reads_timestamptz() -> None:
    """AT-21 · `trades_plain` (which has a `TIMESTAMP` column) read via Athena ·
    expected strategy **S1**.

    Pass criteria: the `validate_reads` Athena leg succeeds on `timestamptz`;
    the record notes the millisecond-precision constraint.
    """
    pytest.fail(_TODO)


def test_at_22_uniform_without_register_bridge() -> None:
    """AT-22 · A UniForm table without `register_bridge` · expected strategy
    **S6**.

    Pass criteria: state `SKIPPED_S6` with zero side effects; with
    `register_bridge=true` the state becomes `FEDERATED` and Athena reads.
    """
    pytest.fail(_TODO)
